name: C/C++ CI Test 

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone private repos
      uses: actions/checkout@v2
      with:
       repository: 'y-majima/a-private-repo-test'
       token: ${{secrets.ACCESS_TOKEN}}
    - name: make
      run: make
    - name: test
      run: ./test
