name: C/C++ CI Test 

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       path: test-github-actions
    - name: clone private repos
      uses: actions/checkout@v2
      with:
       repository: 'y-majima/a-private-repo-test'
       token: ${{secrets.ACCESS_TOKEN}}
       path: a-private-repo-test
    - name: make
      run: cd $GITHUB_WORKSPACE/test-github-actions && make
    - name: test
      run: $GITHUB_WORKSPACE/test-github-actions/test
